### ISSUE TITLE
Win32/Bitrep.A    Trojan Detected???

### ISSUE THREAD

**Issue by capitalprize** [exclfork/ExclusiveCoin#12]
Windows Defender indicates a Severe Alert Level with a Win32/Bitrep.A Trojan in the exclusivecoin-qt.exe download, application is sent to quarantine and is removed before blockchain syncs. Subsequent attempt to load program result in Windows 10 deleting program.

Nice Wallet though it gets deleted

**Comment by exclfork** [comment]
will check with developer, thanks!
